---
# tasks file for postgis

- name: Add postgres apt repo
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main' state=present

- apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc validate_certs=no state=present

- name: install common useful devtools(git/tig/htop/meld/curl/wget/gdebi)
  apt: pkg={{ item }} state=installed force=yes
  with_items:
    - postgresql-9.4
    - postgresql-client-9.4
    - postgresql-9.4-postgis-2.1
    - postgresql-9.4-postgis-2.1-scripts
